# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab11982cc57b1196ccc59bb3f9ed9c6cdd16696304e2b7b6aa96006a6089861c99c4e9161cda34e20f00ac25c494bb856be0ef1324e1c4dafd63b76a20c9990

test:
  secret_key_base: af0eef456ce24444ed0a94882e5caf86e239b0cacd59078710feb3da908f9e3e2b3574a08400f2e24c441830f93a37be6eb31023ca8f45a61203c4d3cbeec357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
